# Лабораторная работа №2
Вариант 9
## Задание 1. Создание и изменение массивов
Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [88]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = 2 * a
b[b > 10] = 0
print(b)

[ 2  4  6  8 10  0  0  0  0]


## Задание 2. Работа с булевыми масками
Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив

In [90]:
a = np.random.randint(1, 101, size=20)
print(a)
print(a[a % 5 == 0])
print(np.where(a % 5 == 0, -1, a))

[74 40 76 68 60 34 45 25 76 48 74 40 83 35 76 89 48 49 49 39]
[40 60 45 25 40 35]
[74 -1 76 68 -1 34 -1 -1 76 48 74 -1 83 -1 76 89 48 49 49 39]


## Задание 3. Объединение и разбиение массивов
Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.
Объедините эти массивы в один двумерный массив (по строкам).
Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.
Выведите все промежуточные и итоговые результаты.

In [118]:
a = np.random.randint(0, 51, size=5)
b = np.random.randint(0, 51, size=5)
print('a =', a)
print('b =', b)
c = np.array([a, b])
print('c =', c)
a1, b1 = c
print('a1 =', a1)
print('b1 =', b1)

a = [35 38 49 23 35]
b = [24 15 34 28 49]
c = [[35 38 49 23 35]
 [24 15 34 28 49]]
a1 = [35 38 49 23 35]
b1 = [24 15 34 28 49]


## Задание 4. Генерация и работа с линейными последовательностями
Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты

In [198]:
a = np.linspace(-10, 10, 50)
print('a =', a, '\n')
print('summ1 =', np.sum(a))
print('summ2 =', np.sum(a[a > 0]))
print('summ3 =', np.sum(a[a < 0]))

a = [-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ] 

summ1 = 7.105427357601002e-15
summ2 = 127.55102040816328
summ3 = -127.55102040816327


## Задание 5. Работа с диагональными и единичными матрицами
Создайте:
Единичную матрицу размером 4×4.
Диагональную матрицу размером 4×4 с диагональными элементами [5,10,15,20] (не использовать циклы).
Найдите сумму всех элементов каждой из этих матриц и сравните результаты

In [218]:
import numpy as np
a = np.eye(4, 4)
print('a =', a, '\n')
b = np.matrix('5 0 0 0; 0 10 0 0; 0 0 15 0; 0 0 0 20')
print('b =', b, '\n')
print('summ1 =', np.sum(a))
print('summ2 =', np.sum(b))

a = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

b = [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]] 

summ1 = 4.0
summ2 = 50


## Задание 6. Создание и базовые операции с матрицами
Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
Их сумму
Их разность
Их поэлементное произведение

In [15]:
import numpy as np
a = np.random.randint(1, 21, size=(3, 3))
b = np.random.randint(1, 21, size=(3, 3))
print(a, b, sep='\n')
print()
print(a + b)
print(a - b)
print(a * b)

[[16 17  8]
 [15  8  7]
 [ 8 19 20]]
[[10 11 20]
 [15 18 14]
 [ 8  8 11]]

[[26 28 28]
 [30 26 21]
 [16 27 31]]
[[  6   6 -12]
 [  0 -10  -7]
 [  0  11   9]]
[[160 187 160]
 [225 144  98]
 [ 64 152 220]]


## Задание 7. Умножение матриц
Создайте две матрицы NumPy:
Первую размером 2×3, заполненную случайными числами от 1 до 10.
Вторую размером 3×2, заполненную случайными числами от 1 до 10.
Выполните матричное умножение ( @ или np.dot ) и выведите результат.

In [19]:
a = np.random.randint(1, 11, size=(2, 3))
b = np.random.randint(1, 11, size=(3, 2))
print(np.dot(a, b))

[[ 40  63]
 [ 55 100]]


## Задание 8. Определитель и обратная матрица
Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
Определитель этой матрицы;
Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена).
Используйте функции np.linalg.det и np.linalg.inv

In [45]:
a = np.random.randint(1, 11, size=(3, 3))
print(a)
print()
b = np.linalg.det(a)
print(b, '\n')
if b == 0:
    print('матрица вырождена')
else:
    print(np.linalg.inv(a))

[[ 9  3  1]
 [ 7  8  2]
 [10  8  6]]

198.00000000000017 

[[ 0.16161616 -0.05050505 -0.01010101]
 [-0.11111111  0.22222222 -0.05555556]
 [-0.12121212 -0.21212121  0.25757576]]


## Задание 9. Транспонирование и след матрицы
Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:
Исходную матрицу;
Транспонированную матрицу;
След матрицы (сумму элементов на главной диагонали);
Используйте np.trace для нахождения следа.
Используйте np.trace для нахождения следа.

In [54]:
a = np.random.randint(1, 51, size=(4, 4))
print(a)
print()
print(a.T)
print()
print(np.trace(a))

[[14 47 12 29]
 [ 9  8 17 29]
 [42 31 30  8]
 [12 43 33  6]]

[[14  9 42 12]
 [47  8 31 43]
 [12 17 30 33]
 [29 29  8  6]]

58


## Задание 10. Системы линейных уравнений

In [68]:
A = np.matrix('2 3 -1; 4 -1 2; -3 5 4')
B = np.matrix('5; 6; -2')
x = np.linalg.solve(A, B)
print("Решение:", np.round(x, 2))

Решение: [[1.64]
 [0.58]
 [0.01]]


## Задание 11. Индивидуальное задание. Вариант 9.
Оптимальный выбор топлива. Автомобиль использует три вида топлива в
разных пропорциях. Бензин даёт 30 МДж энергии на литр, дизель — 35 МДж, газ — 25 МДж. Для поездки требуется 100 МДж энергии. Водитель хочет использовать бензина в два раза больше, чем газа, а количество дизеля равно количеству газа. Сколько литров каждого топлива нужно залить?
$$
\begin{cases}
30x + 35y + 25z = 100 \\
x - 2z = 0 \\
y - z = 0
\end{cases}
$$

In [84]:
A = np.array([[30, 35, 25], [1, 0, -2], [0, 1, -1]])
B = np.array([100, 0, 0])
det_A = np.linalg.det(A)
A_x = A.copy()
A_x[:, 0] = B
det_x = np.linalg.det(A_x)
A_y = A.copy()
A_y[:, 1] = B
det_y = np.linalg.det(A_y)
A_z = A.copy()
A_z[:, 2] = B
det_z = np.linalg.det(A_z)
x = det_x / det_A
y = det_y / det_A
z = det_z / det_A
print("Метод Крамера:")
print(f"x = {x:.2f} л, y = {y:.2f} л, z = {z:.2f} л")
print()
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Матричный метод:")
print(f"x = {X[0]:.2f} л, y = {X[1]:.2f} л, z = {X[2]:.2f} л")
print()
X = np.linalg.solve(A, B)
print("Метод np.linalg.solve:")
print(f"x = {X[0]:.2f} л, y = {X[1]:.2f} л, z = {X[2]:.2f} л")

Метод Крамера:
x = 1.67 л, y = 0.83 л, z = 0.83 л

Матричный метод:
x = 1.67 л, y = 0.83 л, z = 0.83 л

Метод np.linalg.solve:
x = 1.67 л, y = 0.83 л, z = 0.83 л
